---
- name: Ensure required base apt packages are installed
  ansible.builtin.apt:
    pkg: "{{ item }}"
    update_cache: true
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gpg
  when: (ansible_facts.os_family == 'Debian')
