---
- name: Ensure required containerd are present
  ansible.builtin.lineinfile:
    path: /etc/modules-load.d/k8s.conf
    line: "{{ item }}"
    create: true
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Ensure required containerd modules are loaded
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - overlay
    - br_netfilter

- name: Ensure containerd systemctl params are present
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/k8s.conf
    line: "{{ item }}"
    create: true
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables  = 1
    - net.bridge.bridge-nf-call-ip6tables = 1
    - net.ipv4.ip_forward                 = 1
